GET http://localhost:8000/api/query-theme/blacked
Accept: application/json

###

GET http://localhost:8000/api/query-theme/lisu
Accept: application/json

###

GET http://localhost:8000/api/query-theme/moebooru
Accept: application/json

###

GET http://localhost:8000/api/query-theme/lewd
Accept: application/json

###

GET http://localhost:8000/api/query/test
Accept: application/json

###



